/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "SD_CMD.h"
#include "SD_CMD_aliases.h"
#include "HOST_CLK.h"
#include "HOST_CLK_aliases.h"
#include "rx.h"
#include "rx_aliases.h"
#include "tx.h"
#include "tx_aliases.h"
#include "SD_CMD_ISR.h"
#include "SD_BYTE_ISR.h"
#include "LED_REQ.h"
#include "LED_REQ_aliases.h"
#include "LED_RSP.h"
#include "LED_RSP_aliases.h"
#include "UART_1_SCBCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

